server:
  port: 81
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
    proxy-user-name: krasus1966
    proxy-password:
ribbon:
  # 建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  # 建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 5000
spring:
  application:
    name: cloud-order-service-eureka
logging:
  level:
    top.krasus1966.springcloud.service.PaymentFeignService: debug
