server:
  port: 8001

spring:
  application:
    name: cloud-payment-service-eureka
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_news?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 196610121



mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: top.krasus1966.springcloud.entities

eureka:
  client:
    # 表示是否将自己注册进 EurekaServer 默认为 true
    register-with-eureka: true
    # 是否从 EurekaServer 抓取已有的注册信息，默认为 true，单节点无所谓，集群必须设置为 true 才能配合 ribbon 使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
       defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    # Eureka客户端向服务器发送心跳的时间间隔，单位为秒，默认为30秒
    lease-renewal-interval-in-seconds: 1
    # Eureka服务端在受到最后一次心跳后等待时间上线，单位为秒，默认是90秒，超时将删除服务
    lease-expiration-duration-in-seconds: 2