server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.9:1111 # nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
