server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #服务端的实例名称
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
#    service-url:
      # 设置与 Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://localhost:7002/eureka
#    proxy-user-name: krasus1966
#    proxy-password:
  server:
    # 关闭自我保护模式 保证不可用服务及时剔除
    enable-self-preservation: false
    # 默认90秒注销
    eviction-interval-timer-in-ms: 2000