server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh          # 路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service-eureka # 匹配后提供服务的路由地址 lb是loadbalanced
          predicates:
            - Path=/payment/get/**   # 断言，路径相匹配的进行路由
           # - After=2020-06-17T20:51:11.622+08:00[Asia/Shanghai] # 在这个时间之后才允许访问
           # - Before
           # - Between
           # - Cookie=username,zzyy # 包含cookie才会允许访问，后面为正则表达式
           # - Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性并且值为整数的正则表达式
           # - Host
           # - Method
           # - Query
        - id: payment_routh2
          # uri: http://localhost:8001
          uri: lb://cloud-payment-service-eureka
          predicates:
            - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service

  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka